/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vOMG2D94tJC
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:
import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

import Logo from "@/components/component/logo";
import HeaderAvatar from "@/components/component/header-avatar";

import { useChat } from "ai/react";

export function ByteChatBot() {
  const { messages, input, handleInputChange, handleSubmit } = useChat();

  return (
    <div className="flex h-screen w-full">
      {/* Main Content */}
      <div className="flex flex-1 flex-col">
        <header className="sticky top-0 z-10 flex justify-between h-14 items-center gap-4 border-b border-slate-200 bg-background px-4 sm:h-[60px] sm:px-6">
          <Logo />

          <HeaderAvatar />
        </header>

        <main className="relative flex-1 overflow-auto pt-5 bg-slate-100 pb-0">
          <div className=" grid gap-6 max-w-5xl m-auto">
            {messages.map((m, i) => {
              if (m.role === "user") {
                {
                  /* User message */
                }
                return (
                  <div key={i} className="flex items-start gap-4 justify-end">
                    <div className="grid gap-1.5 rounded-full bg-primary p-3 px-4">
                      <p className="text-white">{m.content}</p>
                    </div>
                  </div>
                );
              } else {
                {
                  /* Chatbot message */
                }
                return (
                  <div key={m.id} className="flex items-start gap-4">
                    <div className="pt-3">
                      <div className="h-[40px] w-[40px] rounded-full bg-slate-400 "></div>
                    </div>

                    <div className="grid gap-1.5 rounded-full p-3 px-4 text-base">
                      <h1 className="font-semibold">Ai Chatbot</h1>
                      <p>{m.content}</p>
                    </div>
                  </div>
                );
              }
            })}
          </div>
          <div className="sticky bottom-0 h-20 bg-gradient-to-b from-transparent to-slate-100"></div>
        </main>

        <form
          onSubmit={handleSubmit}
          className="pb-[20px] bg-slate-100
        px-5"
        >
          <div className="rounded-lg max-w-5xl m-auto sticky bottom-0 z-10 flex h-14 items-center gap-2 border bg-background px-4 sm:h-[60px] sm:px-3">
            <Input
              type="text"
              placeholder="Type your message..."
              className="flex-1 bg-transparent p-2 placeholder:text-base"
              onChange={handleInputChange}
            />

            <Button variant="ghost" size="icon" className="bg-none">
              <PlusIcon />
              <span className="sr-only">More</span>
            </Button>

            <Button variant="default" size="icon" className="bg-primary">
              <SendIcon />
              <span className="sr-only">Send</span>
            </Button>
          </div>
          <p className="text-sm text-center pt-3 text-slate-500">
            This AI chatbot is for informational purposes only and should not be
            considered professional advice.
          </p>
        </form>
      </div>
    </div>
  );
}

function SendIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="white"
      className="size-5"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M6 12 3.269 3.125A59.769 59.769 0 0 1 21.485 12 59.768 59.768 0 0 1 3.27 20.875L5.999 12Zm0 0h7.5"
      />
    </svg>
  );
}

function PlusIcon() {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill="none"
      viewBox="0 0 24 24"
      stroke-width="1.5"
      stroke="#64748b"
      className="size-7"
    >
      <path
        stroke-linecap="round"
        stroke-linejoin="round"
        d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"
      />
    </svg>
  );
}
